openapi: 3.0.1
info:
  title: GapCure API
  description: GapCure API.
  version: '1.0'
servers:
  # Servers
  - url: http://20.204.216.242
  - url: https://20.204.216.242
tags:  
  - name: Patient
    description: Patient API
paths:
  /patient:
    post:
      tags:
        - Patient
      summary: PostPatient
      requestBody:
        description: PostPatient Payload
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Patient'
      description: Post Patient API.
      operationId: PostPatient
      responses:
        '201':
          description: Created
          content:
            application/vnd.collection+json:
              schema:
                $ref: '#/components/schemas/PatientPostResponseModel'
        '401':
          description: '401 response: Unauthorized Request'
          content:
            application/vnd.collection+json:
              schema:
                $ref: '#/components/schemas/CommonErrorResponseModel'

        '404':
          description: '404 response: No Data Found'
          content:
            application/vnd.collection+json:
              schema:
                $ref: '#/components/schemas/CommonErrorResponseModel'
        '500':
          description: Internal Server Error
          content:
            application/vnd.collection+json: {}
    get:
      tags:
        - Patient
      summary: GetPatient
      description: Get Patient API.
      operationId: GetPatient
      responses:
        '200':
          description: OK
          content:
            application/vnd.collection+json:
              schema:
                $ref: '#/components/schemas/PatientGetResponseModel'
        '401':
          description: '401 response: Unauthorized Request'
          content:
            application/vnd.collection+json:
              schema:
                $ref: '#/components/schemas/CommonErrorResponseModel'

        '404':
          description: '404 response: No Data Found'
          content:
            application/vnd.collection+json:
              schema:
                $ref: '#/components/schemas/CommonErrorResponseModel'
        '500':
          description: Internal Server Error
          content:
            application/vnd.collection+json: {}
  /patient/{id}:
    get:
      tags:
        - Patient
      summary: GetPatientById
      description: Get Patient by Id API.
      operationId: GetPatientById
      parameters:
        - name: id
          in: path
          description: Patient Id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/vnd.collection+json:
              schema:
                $ref: '#/components/schemas/PatientDetailResponseModel'
        '401':
          description: '401 response: Unauthorized Request'
          content:
            application/vnd.collection+json:
              schema:
                $ref: '#/components/schemas/CommonErrorResponseModel'

        '404':
          description: '404 response: No Data Found'
          content:
            application/vnd.collection+json:
              schema:
                $ref: '#/components/schemas/CommonErrorResponseModel'
        '500':
          description: Internal Server Error
          content:
            application/vnd.collection+json: {}

    patch:
      tags:
        - Patient
      summary: Patch Patient By Id
      description: Patch Patient by Id API.
      operationId: Patch
      parameters:
        - name: id
          in: path
          description: Patient Id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Success
          content:
            application/vnd.collection+json: {}
        '401':
          description: '401 response: Unauthorized Request'
          content:
            application/vnd.collection+json:
              schema:
                $ref: '#/components/schemas/CommonErrorResponseModel'

        '404':
          description: '404 response: No Data Found'
          content:
            application/vnd.collection+json:
              schema:
                $ref: '#/components/schemas/CommonErrorResponseModel'
        '500':
          description: Internal Server Error
          content:
            application/vnd.collection+json: {}
  
components:
  schemas:
    Patient:
      type: object
      required:
        - uniqueId
        - name
        - address
      properties:
        uniqueId:
          type: string
          minLength: 24
          maxLength: 24
        name:
          type: string
          minLength: 1
          maxLength: 100
        address:
          type: string
          minLength: 1
          maxLength: 200
    PatientPostResponseModel:
      type: 'object'
      properties:
        data:
          type: object
          properties:
            patient:
              type: 'object'
              properties:
                id:
                  type: string
                uniqueId:
                  type: string
                name:
                  type: string
                metaData:
                  type: object
                  properties:
                    yesCount:
                      type: number
                    noCount:
                      type: number
    PatientGetResponseModel:
      type: 'object'
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              uniqueId:
                type: string
              name:
                type: string
              metaData:
                type: object
                properties:
                  yesCount:
                    type: number
                  noCount:
                    type: number
    PatientDetailResponseModel:
      type: 'object'
      properties:
        data:
          type: object
          properties:
            patient:
              type: 'object'
              properties:
                id:
                  type: string
                uniqueId:
                  type: string
                name:
                  type: string
                metaData:
                  type: object
                  properties:
                    yesCount:
                      type: number
                    noCount:
                      type: number
    CommonErrorResponseModel:
      type: 'object'
      title: 'ErrorSchema'
      properties:
        errorMessage:
          type: 'string'
        errorCode:
          type: 'number'
    General:
      type: object

  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: []
  - apiKeyQuery: []
