openapi: 3.0.1
info:
  title: GapCure API
  description: GapCure API.
  version: '1.0'
servers:
  # Servers
  - url: http://20.204.216.242
  - url: https://20.204.216.242
tags:  
  - name: Patient
    description: Patient API
paths:
  /patient:
    post:
      tags:
        - Patient
      summary: GetPythoScore
      requestBody:
        description: GetPythoScore Payload
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Patient'
      description: Post GetPythoScore API.
      operationId: GetPythoScore
      responses:
        '201':
          description: Created
          content:
            application/vnd.collection+json:
              schema:
                $ref: '#/components/schemas/PatientPostResponseModel'
        '401':
          description: '401 response: Unauthorized Request'
          content:
            application/vnd.collection+json:
              schema:
                $ref: '#/components/schemas/CommonErrorResponseModel'

        '404':
          description: '404 response: No Data Found'
          content:
            application/vnd.collection+json:
              schema:
                $ref: '#/components/schemas/CommonErrorResponseModel'
        '500':
          description: Internal Server Error
          content:
            application/vnd.collection+json: {}
    get:
      tags:
        - Patient
      paths:
       /patient/get-excel-data:   
      summary: getExcelData
      description: Get getExcelData API.
      operationId: getExcelData
      responses:
        '200':
          description: OK
          content:
            application/vnd.collection+json:
              schema:
                $ref: '#/components/schemas/PatientGetResponseModel'
        '401':
          description: '401 response: Unauthorized Request'
          content:
            application/vnd.collection+json:
              schema:
                $ref: '#/components/schemas/CommonErrorResponseModel'

        '404':
          description: '404 response: No Data Found'
          content:
            application/vnd.collection+json:
              schema:
                $ref: '#/components/schemas/CommonErrorResponseModel'
        '500':
          description: Internal Server Error
          content:
            application/vnd.collection+json: {}
            
  /patient/{id}:
    get:
      tags:
        - Patient
      summary: GetPatientById
      description: Get Patient by Id API.
      operationId: GetPatientById
      parameters:
        - name: id
          in: path
          description: Patient Id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/vnd.collection+json:
              schema:
                $ref: '#/components/schemas/PatientDetailResponseModel'
        '401':
          description: '401 response: Unauthorized Request'
          content:
            application/vnd.collection+json:
              schema:
                $ref: '#/components/schemas/CommonErrorResponseModel'

        '404':
          description: '404 response: No Data Found'
          content:
            application/vnd.collection+json:
              schema:
                $ref: '#/components/schemas/CommonErrorResponseModel'
        '500':
          description: Internal Server Error
          content:
            application/vnd.collection+json: {}

    patch:
      tags:
        - Patient
      summary: Patch Patient By Id
      description: Patch Patient by Id API.
      operationId: Patch
      parameters:
        - name: id
          in: path
          description: Patient Id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Success
          content:
            application/vnd.collection+json: {}
        '401':
          description: '401 response: Unauthorized Request'
          content:
            application/vnd.collection+json:
              schema:
                $ref: '#/components/schemas/CommonErrorResponseModel'

        '404':
          description: '404 response: No Data Found'
          content:
            application/vnd.collection+json:
              schema:
                $ref: '#/components/schemas/CommonErrorResponseModel'
        '500':
          description: Internal Server Error
          content:
            application/vnd.collection+json: {}
  
components:
  schemas:
    Patient:
      type: object
      required:
        - id
        - identifier
        - active
        - gender
        - name
        - birthDate  
        - address
        - deceasedBoolean
        - maritalStatus
        - multipleBirthBoolean
        - photo 
        - contact
        - communication
        - generalPractitioner 
        - managingOrganization
        - link
        - pythoScore      
      properties:
        id:
          type: string
          minLength: 24
          maxLength: 24
        identifier:
          type: string
          minLength: 1
          maxLength: 100
        name:
          type: string
          minLength: 1
          maxLength: 200
        active:
          type: boolean
          minLength: 1
          maxLength: 200  
        gender:
          type: string
          minLength: 1
          maxLength: 200  
        birthDate:
          type: string
          minLength: 1
          maxLength: 200  
        address:
          type: array
          minLength: 1
          maxLength: 200 
        deceasedBoolean:
          type: boolean
          minLength: 24
          maxLength: 24
        maritalStatus:
          type: string
          minLength: 1
          maxLength: 100
        multipleBirthBoolean:
          type: boolean
          minLength: 1
          maxLength: 200
        contact:
          type: array
          minLength: 1
          maxLength: 200  
        communication:
          type: array
          minLength: 1
          maxLength: 200  
        generalPractitioner:
          type: array
          minLength: 1
          maxLength: 200  
        managingOrganization:
          type: array
          minLength: 1
          maxLength: 200
        link:
          type: array
          minLength: 1
          maxLength: 200  
        pythoScore:
          type: string
          minLength: 1
          maxLength: 200                         
    PatientPostResponseModel:
      type: 'object'
      properties:
        data:
          type: object
          properties:
            patient:
              type: 'object'
              properties:
                id:
                  type: string
                identifier:
                  type: string
                active:
                  type: boolean
                name:
                  type: string
                gender:
                  type: string
                birthDate:
                  type: string
                deceasedBoolean:
                  type: boolean
                address:
                  type: array
                maritalStatus:
                  type: string
                multipleBirthBoolean:
                  type: boolean  
                photo:
                  type: array
                contact:
                  type: array
                communication:
                  type: array
                generalPractitioner:
                  type: array
                managingOrganization:
                  type: array  
                link:
                  type: array 
                pythoScore:
                  type: string                   
    PatientGetResponseModel:
      type: 'object'
      properties:
        data:
          type: array
          items:
            type: object
            properties:
                id:
                  type: string
                identifier:
                  type: string
                active:
                  type: boolean
                name:
                  type: string
                gender:
                  type: string
                birthDate:
                  type: string
                deceasedBoolean:
                  type: boolean
                address:
                  type: array
                maritalStatus:
                  type: string
                multipleBirthBoolean:
                  type: boolean  
                photo:
                  type: array
                contact:
                  type: array
                communication:
                  type: array
                generalPractitioner:
                  type: array
                managingOrganization:
                  type: array  
                link:
                  type: array 
                pythoScore:
                  type: string  
    PatientDetailResponseModel:
      type: 'object'
      properties:
        data:
          type: object
          properties:
            patient:
              type: 'object'
              properties:
                id:
                  type: string
                identifier:
                  type: string
                active:
                  type: boolean
                name:
                  type: string
                gender:
                  type: string
                birthDate:
                  type: string
                deceasedBoolean:
                  type: boolean
                address:
                  type: array
                maritalStatus:
                  type: string
                multipleBirthBoolean:
                  type: boolean  
                photo:
                  type: array
                contact:
                  type: array
                communication:
                  type: array
                generalPractitioner:
                  type: array
                managingOrganization:
                  type: array  
                link:
                  type: array 
                pythoScore:
                  type: string  
    CommonErrorResponseModel:
      type: 'object'
      title: 'ErrorSchema'
      properties:
        errorMessage:
          type: 'string'
        errorCode:
          type: 'number'
    General:
      type: object

  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: []
  - apiKeyQuery: []
