openapi: 3.0.1
info:
  title: Pytho Score API
  description: Pytho Score API.
  version: '1.0'
servers:
  # Servers
  - url: http://20.204.216.242
  - url: https://20.204.216.242
tags:  
  - name: Patient
    description: Patient API
paths:
  /patient:
    post:
      tags:
        - Patient
      summary: PostPatient
      requestBody:
        description: PostPatient Payload
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Patient'
      description: Post Patient API.
      operationId: PostPatient
      responses:
        '201':
          description: Created
          content:
            application/vnd.collection+json:
              schema:
                $ref: '#/components/schemas/PatientPostResponseModel'
        '401':
          description: '401 response: Unauthorized Request'
          content:
            application/vnd.collection+json:
              schema:
                $ref: '#/components/schemas/CommonErrorResponseModel'

        '404':
          description: '404 response: No Data Found'
          content:
            application/vnd.collection+json:
              schema:
                $ref: '#/components/schemas/CommonErrorResponseModel'
        '500':
          description: Internal Server Error
          content:
            application/vnd.collection+json: {}
  /patient/pytho-score:
    post:
      tags:
        - PythoScore
      summary: Post PythoScore
      requestBody:
        description: Post PythoScore Payload
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Patient'
      description: Post PythoScore API.
      operationId: PostPythoScore
      responses:
        '200':
          description: OK
          content:
            application/vnd.collection+json:
              schema:
                $ref: '#/components/schemas/PatientPostResponseModel'
        '401':
          description: '401 response: Unauthorized Request'
          content:
            application/vnd.collection+json:
              schema:
                $ref: '#/components/schemas/CommonErrorResponseModel'

        '404':
          description: '404 response: No Data Found'
          content:
            application/vnd.collection+json:
              schema:
                $ref: '#/components/schemas/CommonErrorResponseModel'
        '500':
          description: Internal Server Error
          content:
            application/vnd.collection+json: {}
            
components:
  schemas:
    Patient:
      type: object
      required:
        - id
        - identifier
        - active
        - gender
        - name
        - birthDate  
        - address
        - deceasedBoolean
        - maritalStatus
        - multipleBirthBoolean
        - contact
      properties:
        id:
          type: string
          minLength: 24
          maxLength: 24
        identifier:
          type: string
          minLength: 1
          maxLength: 25
        address:
          type: array
          items:
            type: object
            properties:
              country:
                type: string
                minLength: 1
                maxLength: 15
              state:
                type: string
                minLength: 1
                maxLength: 15
              city:
                type: string
                minLength: 1
                maxLength: 12
              locality:
                type: string
                minLength: 1
                maxLength: 20
        contact:
          type: array
          items:
            type: object
            properties:
              relationship:
                type: string
                minLength: 1
                maxLength: 20
              name:
                type: string
                minLength: 1
                maxLength: 50
              telecom:
                type: array
                items:
                  type: object
                  properties:
                    phone:
                      type: string
                      minLength: 1
                      maxLength: 15
              address:
                type: object
                properties:
                  country:
                    type: string
                  state:
                    type: string
                  city:
                    type: string
                  locality:
                    type: string
              gender:
                type: string
              organization:
                type: string
              period:
                type: object
                properties:
                  time:
                    type: string
                    format: date-time
        communication:
          type: array
          items:
            type: object
            properties:
              language:
                type: string
              preferred:
                type: boolean
        generalPractitioner:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                minLength: 1
                maxLength: 20
              contact_number:
                type: string
                minLength: 1
                maxLength: 14
        managingOrganization:
          type: object
          properties:
            name:
              type: string
              minLength: 1
              maxLength: 14
            contact_number:
              type: string
              minLength: 1
              maxLength: 14
        link:
          type: array
          items:
            type: object
            properties:
              url:
                type: string
        pythoScore:
          type: string
          minLength: 1
          maxLength: 25                    
    PatientPostResponseModel:
      type: 'object'
      properties:
        data:
          type: object
          properties:
            patient:
              type: 'object'
              properties:
                id:
                  type: string
                identifier:
                  type: string
                active:
                  type: boolean
                name:
                  type: string
                gender:
                  type: string
                birthDate:
                  type: string
                deceasedBoolean:
                  type: boolean
                address:
                  type: array
                  items: # Specify the items field for array
                    type: object
                maritalStatus:
                  type: string
                multipleBirthBoolean:
                  type: boolean
                photo:
                  type: array
                  items: # Specify the items field for array
                    type: object
                contact:
                  type: array
                  items: # Specify the items field for array
                    type: object
                communication:
                  type: array
                  items: # Specify the items field for array
                    type: object
                generalPractitioner:
                  type: array
                  items: # Specify the items field for array
                    type: object
                managingOrganization:
                  type: array
                  items: # Specify the items field for array
                    type: object
                link:
                  type: array
                  items: # Specify the items field for array
                    type: object
                pythoScore:
                  type: string

    CommonErrorResponseModel:
      type: 'object'
      title: 'ErrorSchema'
      properties:
        errorMessage:
          type: 'string'
        errorCode:
          type: 'number'
    General:
      type: object

  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: []
  - apiKeyQuery: []