openapi: 3.0.1
info:
  title: Pytho Score API
  description: Pytho Score API.
  version: '1.0'
servers:
  # Servers
  - url: http://34.200.236.229:8081/
  - url: http://34.200.236.229:8081/
tags:  
  - name: Patient
    description: Patient API

paths:
  /patient/pytho-score:
    post:
      tags:
        - Patient
      summary: Post PythoScore
      requestBody:
        description: Post PythoScore Payload
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostPythoScorePayload'
      description: Post PythoScore API.
      operationId: PostPythoScore
      responses:
        '200':
          description: OK
          content:
            application/vnd.collection+json:
              schema:
                $ref: '#/components/schemas/PostPythoScoreResponse'
        '401':
          description: '401 response: Unauthorized Request'
          content:
            application/vnd.collection+json:
              schema:
                $ref: '#/components/schemas/CommonErrorResponseModel'

        '404':
          description: '404 response: No Data Found'
          content:
            application/vnd.collection+json:
              schema:
                $ref: '#/components/schemas/CommonErrorResponseModel'
        '500':
          description: Internal Server Error
          content:
            application/vnd.collection+json: {}
            
components:
  schemas:
    PostPythoScorePayload:
      type: object
      required:
        - identifier
      properties:
        identifier:
          type: string
          minLength: 1
          maxLength: 25            
    PostPythoScoreResponse:
      type: 'object'
      properties:
        data:
          type: object
          properties:
            patient:
              type: 'object'
              properties:
                id:
                  type: string
                identifier:
                  type: string
                active:
                  type: boolean
                name:
                  type: string
                gender:
                  type: string
                birthDate:
                  type: string
                deceasedBoolean:
                  type: boolean
                address:
                  type: array
                  items: # Specify the items field for array
                    type: object
                maritalStatus:
                  type: string
                multipleBirthBoolean:
                  type: boolean
                photo:
                  type: array
                  items: # Specify the items field for array
                    type: object
                contact:
                  type: array
                  items: # Specify the items field for array
                    type: object
                communication:
                  type: array
                  items: # Specify the items field for array
                    type: object
                generalPractitioner:
                  type: array
                  items: # Specify the items field for array
                    type: object
                managingOrganization:
                  type: array
                  items: # Specify the items field for array
                    type: object
                link:
                  type: array
                  items: # Specify the items field for array
                    type: object
                pythoScore:
                  type: string

    CommonErrorResponseModel:
      type: 'object'
      title: 'ErrorSchema'
      properties:
        errorMessage:
          type: 'string'
        errorCode:
          type: 'number'
    General:
      type: object

  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: []
  - apiKeyQuery: []